// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdW-792IbcIu4OkpsU2gMi2Ow05D34h98',
    appId: '1:384529928476:web:d29e1182dd63c09b256ad9',
    messagingSenderId: '384529928476',
    projectId: 'crowd-monitor-4ac40',
    authDomain: 'crowd-monitor-4ac40.firebaseapp.com',
    storageBucket: 'crowd-monitor-4ac40.appspot.com',
    measurementId: 'G-N577QPMRPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQu_K64WbyMttu7fjy8dMJUZQ-nzXIztU',
    appId: '1:384529928476:android:100fe2dcf0c1a0e4256ad9',
    messagingSenderId: '384529928476',
    projectId: 'crowd-monitor-4ac40',
    storageBucket: 'crowd-monitor-4ac40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrtpsggdNrCQTtF8mS4i61iO0pBiSNDcs',
    appId: '1:384529928476:ios:10c4e4884cc99ae7256ad9',
    messagingSenderId: '384529928476',
    projectId: 'crowd-monitor-4ac40',
    storageBucket: 'crowd-monitor-4ac40.appspot.com',
    iosClientId: '384529928476-8hoti4isbetrmoihgk55kq9c9rq3bisi.apps.googleusercontent.com',
    iosBundleId: 'com.example.crowdMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrtpsggdNrCQTtF8mS4i61iO0pBiSNDcs',
    appId: '1:384529928476:ios:10c4e4884cc99ae7256ad9',
    messagingSenderId: '384529928476',
    projectId: 'crowd-monitor-4ac40',
    storageBucket: 'crowd-monitor-4ac40.appspot.com',
    iosClientId: '384529928476-8hoti4isbetrmoihgk55kq9c9rq3bisi.apps.googleusercontent.com',
    iosBundleId: 'com.example.crowdMonitor',
  );
}
